config/routes.rb
  Dot::Application.routes.draw do

  resources :dotobjecttexts do
    member do
      post :votefor
      post :voteagainst
    end
  end

  get "sessions/home"
  
  get "sessions/login"

  get "sessions/setting"

  get "users/ban_user"

  get "users/unban_user"

  get "sessions/follow_user"

  resources :users

  get "home/index"

  root :to => 'sessions#home'
  match "home", :to => "sessions#home"
	match "signup", :to => "users#new"
	match "login", :to => "sessions#login"
	match "logout", :to => "sessions#logout"
	match "/user/profile", :to => "sessions#profile", :as => :profile, :via => [:get]
  match "/dots/text/", :to => "dotobjecttexts#show", :as => :view_text_dot, :via => [:get]
	match "setting", :to => "sessions#setting"
	match "login_attempt", to: "sessions#login_attempt", :as => :login_attempt
  match "/user/follow_user/:id", :to => "sessions#follow_user", :as => :follow_user
  match "/users/ban_user/:id", :to => "users#ban_user"
  match "/users/unban_user/:id", :to => "users#unban_user"
  match "/post/text", :to => "dotobjecttexts#new"
  match "myhome", :to => "sessions#feed"
  match "/users/invalid_user", :to => "sessions#invalid_user"
  match "/comments/create", :to => "comments#create", :as => :comment_create
  match "/directory", :to => "sessions#directory", :as => :directory

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'digest'
  attr_accessible :age, :joined, :name, :password_hash, :salt, :password, :avatar, :title
  attr_accessor :password

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/:style/missing.png"

  acts_as_voter
  
  has_many :dotobjecttexts

  acts_as_follower
  acts_as_followable

  def password=(value)
	if value.present?
	  self.salt = (0...10).map{(65+rand(26)).chr}.join
	  self.password_hash = Digest::SHA256.hexdigest(value + self.salt)
	end
	return @password = value
  end

  def moderatorpriv?
  	self.title == 3 or self.title == 5
  end


  def authenticate?(try)
	Digest::SHA256.hexdigest(try + self.salt) == self.password_hash
  end
	
  def self.authenticator(namea="",pass="")
	user = self.find(:first, :conditions => [ "lower(name) = ?", namea.downcase ])
	return user.authenticate?(pass) ? user : nil if user
	return nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
 # before filter :check_for_current_user, only: [:new]
 #Let it be known that on 15-05-13, a missing underscore on this line caused aprox. 8 hours of grief.
  before_filter :authenticator, only: [:index, :new, :edit, :show, :ban_user, :unban_user]
  before_filter :save_login_state, only:[:new]
  


  
  def index
    if @current_user
      if !@current_user.moderatorpriv?
        flash[:error] = "You don't have the permissions to do that!"
        redirect_to(controller: "sessions", action:"home")
      end
      @users = User.all.sort_by{|e| e[:id]}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  else
    flash[:error] = "You don't have the permissions to do that!"
        redirect_to(controller: "sessions", action:"home")
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if @current_user
      redirect_to(action: 'home') and return
    end

    @user = User.new

    respond_to do |format|
      format.html
    end
  end



  def ban_user
    @user = User.find(params[:id])
    if @current_user and @user.banned == false
      if (@current_user.moderatorpriv?) and @user.title != 5
        @user.banned = true
        @user.reason = "Innapropriate content."
        @user.banner = @current_user.name
        @name = @user.name
        @user.save
        flash[:notice] = "User Banned!"
        redirect_to action: 'index'
      elsif (@current_user.moderatorpriv?) and @user.title == 5
        flash[:error] = "User is an admin! Cannot ban!"
        redirect_to action: 'index'
      end
      else
        flash[:error] = "You don't have those permissions!"
        redirect_to action: 'index'
    end
  end

  def unban_user
    @user = User.find(params[:id])
    if @current_user and @user.banned = true
      if @current_user.moderatorpriv?
        @user.banned = false
        @user.reason = ""
        @user.banner = ""
        @user.save
        flash[:notice] = "User Unbanned!"
        redirect_to action: 'index'
      end
      else
        flash[:error] = "You don't have those permissions!"
        redirect_to action: 'index'
    end
  end

 

  # GET /users/1/edit
  def edit
    if @current_user
      @user = User.find params[:user]
      if @current_user.title != 5 and @current_user != @user
        redirect_to(action: 'home')
      end
    else 
      redirect_to(action: 'home')
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.joined = Time.now
    if User.find(:first, :conditions => [ "lower(name) = ?", @user.name.downcase ]) == nil
      if @user.save
        flash[:notice] = "Account Created! Log in to get started!"
        redirect_to controller:'sessions', action:"home"
      else
        flash[:error] = "Error ecountered while creating account!"
      end
    else
      flash[:error] = "A user with that name already exists!"
      redirect_to controller:'sessions', action:"home"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = "Account Updated! Log in to get started!"
        redirect_to(controller:'sessions', action:"home")
      else
        flash[:error] = "Error encountered while updating account!"
        redirect_to(controller:'sessions', action:"home")
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Username:" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Password:" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Age:" %>
    <%= f.select :age, (0..144) %>
  </div>
  <div class="field">
    <%= f.label "Photo:" %>
    <%= f.file_field :avatar %>
  </div>
  
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<nav>
<% if @current_user and(@current_user.title == 5 or @current_user.title == 3) %>
<a href = "/users">Mod Panel</a> |
<%end%>
<a href = "/users/new"> Sign Up</a> |
<a href = "/sessions/home">Home</a>
<% if @current_user %>
| <%= link_to 'Profile', sessions_profile_path(:id => @current_user.id)%>
| <%= link_to 'Logout', logout_path %>
| <b> Logged in as <%=@current_user.name%>. </b>
<% end %>
<div class="logo">
</nav>
<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div id="pageText">
<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
 <% end %>
<h1>Moderator Panel</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Joined</th>
    <th>NOP(Text)</th>
    <th></th>
    <th></th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><b><%= link_to user.name, profile_path(:id => user.id) %></b></td>
    <td><%= user.age %></td>
    <td><%= user.joined %></td>
    <td><%= Dotobjecttext.where(:creator => user.id).count %>
    <%if user.title != 5 %>
    <%if user.banned %>
    <td><b><%= link_to 'Unban', users_unban_user_path(:id => user.id)%></b></td>
    <%else%>
    <td><b><%= link_to 'Ban', users_ban_user_path(:id => user.id)%></b></td>
    <%end%>
    <%end%>
    <br>
  </tr>
<% end %>
</table>

<br />
</div>

app/views/users/new.html.erb
<div id="pageText">
<h1>Sign Up</h1>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
 <% end %>

<% if @current_user and (@current_user.title == 5 or @current_user.title == 3) %>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password hash:</b>
  <%= @user.password_hash %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>

<p>
  <b>Joined:</b>
  <%= @user.joined %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<footer>
<hr>
<a href="http://dotsitenews.tumblr.com/"><img src="/assets/tumblr.png" height=25px width=25px></a>
<a href="https://twitter.com/TheDotTeam"><img src="/assets/twitter.png" height=25px width=25px></a>
<br>
<b>Copyright © 2013 Dot Ltd. All rights reserved </b> 
</footer>
<%else%>
<%flash[:error] = "You don't have those permissions!"%>
<%redirect_to(controller: "sessions", action:"home")%>
<%end%>