config/routes.rb
  Dot::Application.routes.draw do

  resources :dotobjecttexts do
    member do
      post :votefor
      post :voteagainst
    end
  end

  get "sessions/home"
  
  get "sessions/login"

  get "sessions/setting"

  get "users/ban_user"

  get "users/unban_user"

  get "sessions/follow_user"

  resources :users

  get "home/index"

  root :to => 'sessions#home'
  match "home", :to => "sessions#home"
	match "signup", :to => "users#new"
	match "login", :to => "sessions#login"
	match "logout", :to => "sessions#logout"
	match "/user/profile", :to => "sessions#profile", :as => :profile, :via => [:get]
  match "/dots/text/", :to => "dotobjecttexts#show", :as => :view_text_dot, :via => [:get]
	match "setting", :to => "sessions#setting"
	match "login_attempt", to: "sessions#login_attempt", :as => :login_attempt
  match "/user/follow_user/:id", :to => "sessions#follow_user", :as => :follow_user
  match "/users/ban_user/:id", :to => "users#ban_user"
  match "/users/unban_user/:id", :to => "users#unban_user"
  match "/post/text", :to => "dotobjecttexts#new"
  match "myhome", :to => "sessions#feed"
  match "/users/invalid_user", :to => "sessions#invalid_user"
  match "/comments/create", :to => "comments#create", :as => :comment_create
  match "/directory", :to => "sessions#directory", :as => :directory

end

app/models/dotobjecttext.rb
class Dotobjecttext < ActiveRecord::Base
  attr_accessible :content, :created, :creator, :desc, :dotdowns, :dotups, :nsfw, :private, :title

  acts_as_voteable

  def canView?(user)
    if user
  	  ((self.creator == user.id) && (self.nsfw == 0 || (self.nsfw != 0 && user.age >= 18))) || user.moderatorpriv?
    else
  	  (self.private == 0 && self.nsfw == 0)
    end
  end
  
  belongs_to :user

  has_many :comments
end

app/controllers/dotobjecttexts_controller.rb
class DotobjecttextsController < ApplicationController

  before_filter :authenticator, only: [:new, :create, :index, :show, :edit, :votefor, :voteagainst]
  # GET /dotobjecttexts
  # GET /dotobjecttexts.json
  def index
    if @current_user == nil
      flash[:error] = "You aren't logged in!"
      redirect_to(controller: "sessions", action:"home")
    else
      @dotobjecttexts = Dotobjecttext.where(creator: @current_user.id)

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @dotobjecttexts }
      end
    end
  end

  # GET /dotobjecttexts/1
  # GET /dotobjecttexts/1.json
  def show
    @dotobjecttext = Dotobjecttext.find(params[:id])
    @comments = Comment.where(:asset => @dotobjecttext.id).reverse
    @newcomment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dotobjecttext }
    end
  end

  # GET /dotobjecttexts/new
  # GET /dotobjecttexts/new.json
  def new
    if @current_user
      @dotobjecttext = Dotobjecttext.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @dotobjecttext }
      end
    else 
      flash[:error] = "You don't have the permissions to do that!"
        redirect_to(controller: "sessions", action:"home")
    end
  end

  # GET /dotobjecttexts/1/edit
  def edit
    @dotobjecttext = Dotobjecttext.find(params[:id])
  end

  # POST /dotobjecttexts
  # POST /dotobjecttexts.json
  def create
    @dotobjecttext = Dotobjecttext.new(params[:dotobjecttext])
    @dotobjecttext.creator = @current_user.id
    @dotobjecttext.created = Time.now
    @dotobjecttext.dotups = 0
    @dotobjecttext.dotdowns = 0
    if @dotobjecttext.nsfw == nil
      @dotobjecttext.nsfw = 0
    end
    if @dotobjecttext.save
      flash[:notice] = "Dot posted!"
      redirect_to controller: "sessions", action:"profile", id: @current_user.id
      else
        flash[:error] = "Error with posting!"
        redirect_to controller: "sessions", action:"profile", id: @current_user.id
    end
  end

  # PUT /dotobjecttexts/1
  # PUT /dotobjecttexts/1.json
  def update
    @dotobjecttext = Dotobjecttext.find(params[:id])

    respond_to do |format|
      if @dotobjecttext.update_attributes(params[:dotobjecttext])
        redirect_to controller:"sessions", action:"profile", id: @current_user.id
      else
        format.html { render action: "edit" }
      end
    end
  end

  #ajaxify this entire thing
  def votefor
    @dotobjecttext = Dotobjecttext.find(params[:id])
    if @dotobjecttext.creator == @current_user.id
      flash[:error] = "You can't UpDot your own post!"
      redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
    else
      if @current_user.voted_against?(@dotobjecttext) == false and @current_user.voted_for?(@dotobjecttext) == false
        @current_user.vote_for(@dotobjecttext)
        flash[:notice] = "UpDotted that post!"
        redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
      elsif @current_user.voted_against?(@dotobjecttext)
        @current_user.unvote_for(@dotobjecttext)
        @current_user.vote_for(@dotobjecttext)
        flash[:notice] = "UpDotted that post!"
        redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
      else
        flash[:error] = "You already UpDotted that post!"
        redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
      end
    end
  end

  def voteagainst
    @dotobjecttext = Dotobjecttext.find(params[:id])
    if @dotobjecttext.creator == @current_user.id
      flash[:error] = "You can't DownDot your own post!"
      redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
    else
      if @current_user.voted_against?(@dotobjecttext) == false and @current_user.voted_for?(@dotobjecttext) == false
        @current_user.vote_against(@dotobjecttext)
        flash[:notice] = "DownDotted that post!"
        redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
      elsif @current_user.voted_for?(@dotobjecttext)
        @current_user.unvote_for(@dotobjecttext)
        @current_user.vote_against(@dotobjecttext)
        flash[:notice] = "DownDotted that post!"
        redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
      else
        flash[:error] = "You already DownDotted that post!"
        redirect_to controller:"sessions", action:"profile", id: @dotobjecttext.creator
    end
  end
  end
 #AAAAAAAJAX!

  # DELETE /dotobjecttexts/1
  # DELETE /dotobjecttexts/1.json
  def destroy
    @dotobjecttext = Dotobjecttext.find(params[:id])
    @dotobjecttext.destroy

    respond_to do |format|
      format.html { redirect_to dotobjecttexts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dotobjecttexts_helper.rb
module DotobjecttextsHelper
end

app/views/dotobjecttexts/_comment.html.erb
<div class = "comment">
	<%=link_to(image_tag(User.where(:id => comment.creator).take(1).fetch(0).avatar.url(:thumb), :alt => User.where(:id => comment.creator).take(1).fetch(0).name, :title => User.where(:id => comment.creator).take(1).fetch(0).name, :class => "avatar"), profile_path(:id => comment.creator)) %>
	<a class = "commentauthor" href = <%=profile_path(:id => comment.creator)%>> <%= User.where(:id => comment.creator).take(1).fetch(0).name%></a><span class="commentdate"> - Posted <%=comment.created_at.to_formatted_s(:long)%></span>
	<p class = "commentcontent"> <%= comment.content %></p>
</div>

app/views/dotobjecttexts/_commentform.html.erb
<%= form_for @newcomment, :url => comment_create_path do |f| %>
	<div class = "newcomment">
	<span class = "commentfield">
		<%= f.text_area :content, size: "30x7", :placeholder => "I think..." %>
	</span>
	<span class = "postcomment">
		<%= f.hidden_field :asset, :value => @dotobjecttext.id %>
		<%= f.submit "Post"%>
	</span>
</div>
<%end%>

app/views/dotobjecttexts/_form.html.erb
<%= form_for(@dotobjecttext) do |f| %>
  <% if @dotobjecttext.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dotobjecttext.errors.count, "error") %> prohibited this dotobjecttext from being saved:</h2>

      <ul>
      <% @dotobjecttext.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Title:" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Description:" %>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label "Contents:" %>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label "Private?" %>
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :nsfw, "NSFW Content?" %>
    <%= f.select(:nsfw, options_for_select([["None",0],["Nudity", 1],["Grimdark",2]])) %>
  </div>
  <div class="actions">
    <%= f.submit "Post" %>
  </div>
<% end %>

app/views/dotobjecttexts/edit.html.erb
<h1>Editing dotobjecttext</h1>

<%= render 'form' %>

<%= link_to 'Show', @dotobjecttext %> |
<%= link_to 'Back', dotobjecttexts_path %>

app/views/dotobjecttexts/index.html.erb
<h1>Listing dotobjecttexts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Desc</th>
    <th>Content</th>
    <th>Created</th>
    <th>Creator</th>
    <th>Dotdowns</th>
    <th>Dotups</th>
    <th>Private</th>
    <th>Nsfw</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dotobjecttexts.each do |dotobjecttext| %>
  <tr>
    <td><%= dotobjecttext.title %></td>
    <td><%= dotobjecttext.desc %></td>
    <td><%= dotobjecttext.content %></td>
    <td><%= dotobjecttext.created %></td>
    <td><%= dotobjecttext.creator %></td>
    <td><%= dotobjecttext.dotdowns %></td>
    <td><%= dotobjecttext.dotups %></td>
    <td><%= dotobjecttext.private %></td>
    <td><%= dotobjecttext.nsfw %></td>
    <td><%= link_to 'Show', dotobjecttext %></td>
    <td><%= link_to 'Edit', edit_dotobjecttext_path(dotobjecttext) %></td>
    <td><%= link_to 'Destroy', dotobjecttext, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dotobjecttext', new_dotobjecttext_path %>

app/views/dotobjecttexts/new.html.erb
<div id="pageText">
	
<h1>New Text Dot</h1>

<%= render 'form' %>
</div>

app/views/dotobjecttexts/show.html.erb
<div id="pageText">
<p  class = "content">
<br>
<%= @dotobjecttext.content %> 
<br>
<br>
</p>
<hr>
<div class = "tconatiner">
<%=link_to(image_tag(User.where(:id => @dotobjecttext.creator).take(1).fetch(0).avatar.url(:thumb), :alt => User.where(:id => @dotobjecttext.creator).take(1).fetch(0).name, :title => User.where(:id => @dotobjecttext.creator).take(1).fetch(0).name, :class => "avatar"), profile_path(:id => @dotobjecttext.creator)) %>
<p class = "title"> <%= @dotobjecttext.title %> </p>
<a class = "author" href = <%=profile_path(:id => @dotobjecttext.creator)%>> <%= User.where(:id => @dotobjecttext.creator).take(1).fetch(0).name%> </a>
<p class = "score"> Score: <%=@dotobjecttext.plusminus%> </p>
</div>
<br>
<p class = "description"> <%= @dotobjecttext.desc %> </p>
<hr class = "drops">
<%= render 'commentform' %>
<div class = "comments">
	<% if !@comments.empty? %>
			<%= render partial:"comment", collection:@comments %>	
	<% else %>
		<br>
		<h1> No comments on this post? Why not post one?</h1>
	<% end %>
</div>
</div>