config/routes.rb
  Dot::Application.routes.draw do

  resources :dotobjecttexts do
    member do
      post :votefor
      post :voteagainst
    end
  end

  get "sessions/home"
  
  get "sessions/login"

  get "sessions/setting"

  get "users/ban_user"

  get "users/unban_user"

  get "sessions/follow_user"

  resources :users

  get "home/index"

  root :to => 'sessions#home'
  match "home", :to => "sessions#home"
	match "signup", :to => "users#new"
	match "login", :to => "sessions#login"
	match "logout", :to => "sessions#logout"
	match "/user/profile", :to => "sessions#profile", :as => :profile, :via => [:get]
  match "/dots/text/", :to => "dotobjecttexts#show", :as => :view_text_dot, :via => [:get]
	match "setting", :to => "sessions#setting"
	match "login_attempt", to: "sessions#login_attempt", :as => :login_attempt
  match "/user/follow_user/:id", :to => "sessions#follow_user", :as => :follow_user
  match "/users/ban_user/:id", :to => "users#ban_user"
  match "/users/unban_user/:id", :to => "users#unban_user"
  match "/post/text", :to => "dotobjecttexts#new"
  match "myhome", :to => "sessions#feed"
  match "/users/invalid_user", :to => "sessions#invalid_user"
  match "/comments/create", :to => "comments#create", :as => :comment_create
  match "/directory", :to => "sessions#directory", :as => :directory

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>

<nav>
<ul>
<li> <a id = "logo" href = "/"> <%=image_tag("dot200x50.png" , :height => '50', :width => '100') %></a></li>
<% if @current_user and(@current_user.title == 5 or @current_user.title == 3) %>
<li><a href = "/users"><i class=" fa fa-lg fa-fw fa-shield"></i>Mod Panel</a></li>
<%end%>
<% if @current_user %>
<li> <%= link_to raw("<i class=\"fa fa-lg fa-fw fa-user\"></i>#{@current_user.name}"), profile_path(:id => @current_user.id) %></li>
<li> <%= link_to raw("<i class=\"fa fa-lg fa-fw fa-sign-out\"></i>Log Out"), logout_path %> </li>
<li> <%= link_to raw("<i class=\"fa fa-lg fa-fw fa-plus-circle\"></i>Post"), post_text_path %> </li>
<li> <%= link_to raw("<i class=\"fa fa-lg fa-fw fa-globe\"></i>Feed"), myhome_path %> </li>
<li> <%= link_to raw("<i class=\"fa fa-lg fa-fw fa-sitemap\"></i>Directory"), directory_path %></li>
<%else%>
<li> <%= link_to raw("<i class=\"fa fa-lg fa-fw fa-sign-in\"></i>Log In"), login_path %> </li>
<li><%= link_to raw("<i class=\"fa fa-lg fa-fw fa-ticket\"></i>Sign Up"), signup_path %></li>
<% end %>
</ul>
</nav>

<%= yield %>

<footer>
<hr>
<a href="https://twitter.com/PunktCreative" class = "socialMediaButton" target="_blank"><i class = "fa fa-2x fa-fw fa-twitter-square"></i></a>
<a href="https://github.com/PunktCreative" class = "socialMediaButton" target="_blank"><i class = "fa fa-2x fa-fw fa-github-square"></i></a>
<a href="http://punktnews.tumblr.com" class = "socialMediaButton" target="_blank"><i class = "fa fa-2x fa-fw fa-tumblr-square"></i></a>
<br>
<b>Copyright © 2013 Punkt Creative Ltd. All rights reserved </b>	
</footer>
</body>
</html>